#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1
else
    allowed_ver=("10")
    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]; then
        echo "Unsupported OpenFOAM version sourced!"
    fi
fi

# Clean Libraries
(echo "Compiling rayTracingLaserSource"  && cd Libraries/rayTracingLaserSource/laserHeatSource && ./Allwclean && cd ../)
(echo "Compiling geometricVoF" && cd Libraries/geometricVoF && ./Allwclean && cd ../)
(echo "Compiling transportModels" && cd Libraries/transportModels/incompressible && ./Allwclean &&  cd ../)
(echo "Compiling turbulenceModels" && cd Libraries/turbulenceModels/incompressible && ./Allwclean &&  cd ../)

# Clean Utilities
(echo "Compiling setSolidFraction" && cd Utilities/setSolidFraction && ./Allwclean && cd ../)

# Clean Solver
(echo "Compiling laserMeltFoam" && cd laserMeltFoam && ./Allwclean && cd ../)

# Clear all build logs
echo; echo "Removing all log.Allwmake build logs"; echo
find . -name log.Allwmake | xargs rm

#------------------------------------------------------------------------------







